version: "3.3"

services:
  backend:
    build: ./backend-app
    restart: unless-stopped
    env_file: ./backend-app/.env
    ports:
      - 8000:8080
    stdin_open: true
    tty: true
    container_name: backend-app
  frontend:
    build: ./frontend-app
    ports:
      - "3000:80"
    container_name: frontend-app

